version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: shop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-network

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-back
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shop_db
      DB_USER: shop_user
      DB_PASSWORD: shop_password
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:dev"]
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shop-network


volumes:
  postgres_data:
    driver: local

networks:
  shop-network:
    driver: bridge
